name: Build

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # 1. 使用腾讯云镜像替换Gradle下载源
      - name: Configure Gradle Mirror
        run: |
          sed -i 's|https\\://services.gradle.org/distributions|https://mirrors.cloud.tencent.com/gradle|' gradle/wrapper/gradle-wrapper.properties
          cat gradle/wrapper/gradle-wrapper.properties  # 验证修改
          
      # 2. 设置更现代的Java环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      # 3. 添加Gradle缓存支持
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # 4. 添加网络调试步骤（调试后可删除）
      - name: Debug network connectivity
        run: |
          echo "Testing connection to mirrors:"
          curl -I https://mirrors.cloud.tencent.com/gradle
          echo "Local DNS resolution:"
          nslookup mirrors.cloud.tencent.com
      
      # 5. 构建步骤（带重试机制）
      - name: Build mod jar
        run: |
          for i in {1..3}; do
            ./gradlew deploy && break || sleep 10
          done
      
      # 6. 上传制品
      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-build
          path: build/libs/*.jar